server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://rememeber-project.c15dkezpex4v.ap-northeast-2.rds.amazonaws.com/remember?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: hippo2003
    password: wns12358
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 269750796517-rinre7c7s0b6al5t7u00oim5eh47edn0.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
          naver:
            client-id: 9_dnPO2aAshpkXkjaOfQ
            client-secret: aJgh1KmYnq
            scope:
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
      
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
coolsms:
  apikey: NCSIYYNDP4GTCCWS
  apisecret: R2QNFN1TTTODSVKB5GBCMTDRQ9BQLWOK
  fromnumber: 01035947111
  
file:
  path: C:/Remember_workspace/Remember_Project/file_upload/
